name: Update Repo & Release (wip)

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
        type: string
      prerelease:
        description: 'Set as a pre-release'
        required: false
        type: boolean
        default: false
      latest:
        description: 'Set as the latest release'
        required: true
        type: boolean
        default: false

jobs:
  print-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tags to STDOUT
        run: echo The tags are ${{ inputs.tags }} 
      - name: Update version numbers in repo
        run: echo placeholder
      - name: Create files in release folder
        run: echo placeholder
      - name: Update files in pre-release folder
        if: ${{ inputs.prerelease }}
        run: echo placeholder
